version: "3.5"
services:
  mysql:
    image: mysql:5.6
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Cmdu1OG2vLfL
      MYSQL_DATABASE: striv
  postgres:
    image: postgres:11
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: striv
      POSTGRES_PASSWORD: Cmdu1OG2vLfL
