name: Deploy striv
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: striv-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: striv-npm-
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: striv-pip-${{ hashFiles('requirements*.txt') }}
          restore-keys: striv-pip-
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          npm install
      - name: Test frontend
        run: |
          npm run test:unit
      - name: Test backend
        run: |
          date
          docker-compose up &
          sleep 60
          date
          echo "Start checking for socket"
          for s in 5 5 5 5 5 5 ; do nc -z 127.0.0.1 3306 && break ; echo "Sleeping $s sec" ; sleep $s ; done
          nc -z 127.0.0.1 5432 || exit 1
          pytest test/
          docker-compose down
      - name: Build Docker image
        run: |
          npm run build
          docker build -t bittrance/striv .
      - name: Deploy
        env:
          DOCKER_SECRET: ${{ secrets.DOCKER_SECRET }}
        run: |
          echo "$DOCKER_SECRET" | docker login --username bittrance --password-stdin
          docker push bittrance/striv
