name: Python package
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine:3.12
    # strategy:
    #   matrix:
    #     python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apk add --no-cache python3 python3-dev py3-pip linux-headers make g++
          pip install -r requirements-dev.txt
      - name: Test with pytest
        run: |
          pytest test/
